export const dummy_user = {
    "name": "Ajmal Mohad",
    "image": "https://picsum.photos/100",
    "username": "ajmalmohad",
}

export const dummy_table = [
    {
        "sl_number": "1",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "2",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "3",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "4",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "5",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "6",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "7",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "8",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "9",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "10",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "11",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "12",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "13",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "14",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "15",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "16",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "17",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "18",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "19",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "20",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "21",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "22",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "23",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "24",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "25",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }, {
        "sl_number": "26",
        "booking_id": "PB105",
        "truck_number": "MAH 560",
        "customer_id": "001",
        "driver_name": "Marvin McKinney",
        "driver_phone": "+60 564531",
        "truck_type": "Van",
        "truck_tonnage": "3 Tonner",
    }
]


export const dummy_table_mapping = [
    ["Sl. No.", "Booking ID", "Truck No.","Customer ID","Driver Name","Driver Phone", "Truck Type","Truck Tonnage"],
    ["sl_number", "booking_id", "truck_number","customer_id","driver_name","driver_phone","truck_type", "truck_tonnage"]
]